eureka:
  instance:
    hostname: localhost
  client:
  service-url:
    default-zone: ${EUREKA_URL:https://discovery-87v3.onrender.com/eureka}

# Disable Eureka from overriding system properties
spring:
  cloud:
    config:
      override.system-properties: false