spring:
  application:
    name: GO-USER-SERVICE
  config:
    import: optional:configserver:https://config-r3jv.onrender.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
